declare function isBoolean(bool: any): boolean;
declare function isNil(nil: any): boolean;
declare function isSymbol(sym: any): boolean;
declare function isJson(str: any): boolean;
declare function isFunction(func: any): boolean;
declare function isObject(object: any): boolean;
declare function isArray(array: any): boolean;
declare function isAscii(code: any, extended?: boolean): boolean;
declare function isInteger(number: any, typeCheck?: boolean): boolean;
declare function isFloat(number: any, typeCheck?: boolean): boolean;
declare function isNumber(number: any, typeCheck?: boolean): boolean;
declare function isString(string: any): boolean;
declare function isHtmlElement(htmlElement: any): boolean;
declare function isHtmlEventAttribute(htmlEventAttribute: any): boolean;
declare function isNode(node: any): boolean;
declare function isRegex(regex: any, typeCheck?: boolean): boolean;
declare function isEven(number: any, typeCheck?: boolean): boolean;
declare function isOdd(number: any, typeCheck?: boolean): boolean;
declare function isOrigin(number: any, typeCheck?: boolean): boolean;
declare function isPositive(number: any, typeCheck?: boolean): boolean;
declare function isNegative(number: any, typeCheck?: boolean): boolean;
declare function isPowerOfTwo(number: any, typeCheck?: boolean): boolean;
declare function isEmail(email: any): boolean;
declare function isIpAddress(ipAddress: any): boolean;
export { isBoolean, isNil, isSymbol, isJson, isFunction, isObject, isArray, isAscii, isInteger, isFloat, isNumber, isString, isHtmlElement, isHtmlEventAttribute, isNode, isEven, isOdd, isOrigin, isPositive, isNegative, isPowerOfTwo, isRegex, isEmail, isIpAddress };